name: 'kdiff'
descrption: "Print kustomize diff output for multiple clusters"
runs: 
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/checkout@v3
      with:
        repository: democracytoday/kdiff
        ref: s/allow-ssh-resources
        path: .github/actions
    - run: sudo apt-get install colordiff ruby zsh
      shell: bash
    - name: fetch pull request target branch
      run: |
        git fetch origin $GITHUB_BASE_REF
        git branch --track $GITHUB_BASE_REF origin/$GITHUB_BASE_REF
      shell: bash
    - name: print kustomize version
      run: kustomize version
      shell: bash
    - name: install ssh key from secret
      run: |
        mkdir -p $HOME/.ssh
        echo $SSH_KEY >> $HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
      shell: bash
    - run: GIT_TRACE=1 ruby .github/actions/kdiff.rb $GITHUB_BASE_REF
      shell: bash
