name: 'kdiff'
descrption: "Print kustomize diff output for multiple clusters"
runs: 
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install colordiff ruby zsh
    - name: fetch pull request target branch
      run: |
        git fetch origin $GITHUB_BASE_REF
        git branch --track $GITHUB_BASE_REF origin/$GITHUB_BASE_REF
    - name: print kustomize version
      run: kustomize version
    - run: ruby script/kdiff.rb $GITHUB_BASE_REF
