name: 'kdiff'
descrption: "Print kustomize diff output for multiple clusters"
runs: 
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: actblue/kdiff
        ref: main
        path: .github/actions
    - run: sudo apt-get install colordiff ruby zsh
      shell: bash
    - name: fetch pull request target branch
      run: |
        git fetch origin $GITHUB_BASE_REF
        git branch --track $GITHUB_BASE_REF origin/$GITHUB_BASE_REF
      shell: bash
    - name: print kustomize version
      run: kustomize version
      shell: bash
    - run: ruby .github/actions/kdiff/kdiff.rb $GITHUB_BASE_REF
      shell: bash
